### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by phelanjo** [phelanjo/tier_list#1]
Updating README file to include:

- Topic/domain of the application
- Names of team members
- How to get the app going
- How to run the test suite

**Comment by MikeWittenburg** [comment]
Dependencies:

First, install Rails framework, % gem install rails
Second, make a project directory % mkdir projectname
Third, create your initial directory structure by entering % rails new .
Forth, you will need to create a database using default SQLite % rake db:create:all
Fifth, set up the file schema.rb that Rails uses to rebuild the test database %rake db:migrate
Sixth, add spec-rails gem to your Gemfile with the following code:
% group :development, :test do
% 	gem "rspec-rails", "~> 3.7.0"
% end
This adds a Rake file that changes the default test to run RSpec.
Seventh, generate installation and spec file infrastructure. This adds with the following:
% bundle install
% rails generate rspec:install



How to run the program:

In the project directory, enter rails s.
To see/use the app, open your browser and navigate to localhost:3000.

How to run the test suite:

In the project directory, enter % rspec

**Comment by MikeWittenburg** [comment]
Dependencies:

First, install Rails framework, % gem install rails
Second, make a project directory % mkdir projectname
Third, create your initial directory structure by entering % rails new .
Forth, you will need to create a database using default SQLite % rake db:create:all
Fifth, set up the file schema.rb that Rails uses to rebuild the test database %rake db:migrate
Sixth, add spec-rails gem to your Gemfile with the following code:
% group :development, :test do
% gem "rspec-rails", "~> 3.7.0"
% end
This adds a Rake file that changes the default test to run RSpec.
Seventh, generate installation and spec file infrastructure. This adds with the following:
% bundle install
% rails generate rspec:install

How to run the program:

In the project directory, enter rails s.
To see/use the app, open your browser and navigate to localhost:3000.

How to run the test suite:

In the project directory, enter % rspec

**Comment by phelanjo** [comment]
I think the only dependencies are Rails and Rspec. We don't have db integration yet, so I don't think we should include it on the README yet. Adding RSpec to the Gemfile is already done (look at the Gemfile on the develop branch). The only thing I'll probably add is that you'll have to pull down the develop branch before any of this because that's where most of our changes will be (but since we're giving him a link to our commits, it may not matter much. I'll have to ask Yong).
